[project]
name = "argsortium-sims"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "snakemake>=9.13.3",
    "stdpopsim>=0.3.0",
]
