# Simulation parameters
species_name: "HomSap"
model_name: "OutOfAfrica_3G09"

# Sample configuration
samples:
  YRI: 1 # Yoruba
  CEU: 1 # Utah Residents (CEPH)
  CHB: 1 # Han Chinese

# Chromosome list for parallelization
contigs:
  - chr22

# Genetic map
genetic_map: "HapMapII_GRCh38"

# Outgroup configuration
add_outgroup: true
outgroup_time: 215000 # generations ago

base_seed: 42 # Each contig gets: base_seed + contig_index

# Output
output_dir: "results/simulations"
